<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\Form\Type\Finder;

use RK\DownlinkModule\Form\Type\Finder\Base\AbstractLinkFinderType;

/**
 * Link finder form type implementation class.
 */
class LinkFinderType extends AbstractLinkFinderType
{
    // feel free to extend the base form type class here
}
