<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\Helper;

use RK\DownlinkModule\Helper\Base\AbstractEntityDisplayHelper;

/**
 * Entity display helper implementation class.
 */
class EntityDisplayHelper extends AbstractEntityDisplayHelper
{
    // feel free to extend the entity display helper here
}
