services:
    # Form field types
    
    rk_downlink_module.form.type.field.multilist:
        class: RK\DownlinkModule\Form\Type\Field\MultiListType
        arguments:
            - "@rk_downlink_module.listentries_helper"
        tags: ['form.type']
