services:
    rk_downlink_module.link_container:
        class: RK\DownlinkModule\Container\LinkContainer
        arguments:
            - "@translator.default"
            - "@router"
            - "@zikula_permissions_module.api.permission"
            - "@zikula_extensions_module.api.variable"
            - "@rk_downlink_module.controller_helper"
        tags: ['zikula.link_container']
