services:
    # Twig extension
    rk_downlink_module.twig_extension:
        class: RK\DownlinkModule\Twig\TwigExtension
        arguments:
            - "@translator.default"
            - "@zikula_extensions_module.api.variable"
            - "@rk_downlink_module.entity_display_helper"
            - "@rk_downlink_module.workflow_helper"
            - "@rk_downlink_module.listentries_helper"
        public: false
        tags:
            - { name: twig.extension }
