<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\Form\Type;

use RK\DownlinkModule\Form\Type\Base\AbstractLinkType;

/**
 * Link editing form type implementation class.
 */
class LinkType extends AbstractLinkType
{
    // feel free to extend the link editing form type class here
}
