<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule;

use RK\DownlinkModule\Base\AbstractAppSettings;

/**
 * Application settings class for handling module variables.
 */
class AppSettings extends AbstractAppSettings
{
    // feel free to add your own methods here
}
