<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule;

use RK\DownlinkModule\Base\AbstractDownlinkEvents;

/**
 * Events definition implementation class.
 */
class DownlinkEvents extends AbstractDownlinkEvents
{
    // feel free to extend the events definition here
}
