<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule;

use RK\DownlinkModule\Base\AbstractRKDownlinkModule;

/**
 * Module implementation class.
 */
class RKDownlinkModule extends AbstractRKDownlinkModule
{
    // custom enhancements can go here
}
