<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\Event;

use RK\DownlinkModule\Event\Base\AbstractFilterLinkEvent;

/**
 * Event implementation class for filtering link processing.
 */
class FilterLinkEvent extends AbstractFilterLinkEvent
{
    // feel free to extend the event class here
}
