<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\Listener;

use RK\DownlinkModule\Listener\Base\AbstractUserListener;

/**
 * Event handler implementation class for user-related events.
 */
class UserListener extends AbstractUserListener
{
    // feel free to enhance the parent methods
}
