<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\Entity;

use RK\DownlinkModule\Entity\Base\AbstractLinkEntity as BaseEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the concrete entity class for link entities.
 * @ORM\Entity(repositoryClass="RK\DownlinkModule\Entity\Repository\LinkRepository")
 * @ORM\Table(name="rk_downli_link",
 *     indexes={
 *         @ORM\Index(name="workflowstateindex", columns={"workflowState"})
 *     }
 * )
 */
class LinkEntity extends BaseEntity
{
    // feel free to add your own methods here
}
