<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\ContentType;

use RK\DownlinkModule\ContentType\Base\AbstractItem;

/**
 * Generic single item display content plugin implementation class.
 */
class Item extends AbstractItem
{
    // feel free to extend the content type here
}
