<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\Form\Handler\Link;

use RK\DownlinkModule\Form\Handler\Link\Base\AbstractEditHandler;

/**
 * This handler class handles the page events of editing forms.
 * It aims on the link object type.
 */
class EditHandler extends AbstractEditHandler
{
    // feel free to extend the base handler class here
}
