<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\DependencyInjection;

use RK\DownlinkModule\DependencyInjection\Base\AbstractRKDownlinkExtension;

/**
 * Implementation class for service definition loader using the DependencyInjection extension.
 */
class RKDownlinkExtension extends AbstractRKDownlinkExtension
{
    // custom enhancements can go here
}
