<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\HookSubscriber;

use RK\DownlinkModule\HookSubscriber\Base\AbstractLinkFormAwareHookSubscriber;

/**
 * Implementation class for form aware hook subscriber.
 */
class LinkFormAwareHookSubscriber extends AbstractLinkFormAwareHookSubscriber
{
    // feel free to add your own convenience methods here
}
