<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\Event\Base;

use Symfony\Component\EventDispatcher\Event;
use RK\DownlinkModule\Entity\LinkEntity;

/**
 * Event base class for filtering link processing.
 */
class AbstractFilterLinkEvent extends Event
{
    /**
     * @var LinkEntity Reference to treated entity instance.
     */
    protected $link;

    /**
     * @var array Entity change set for preUpdate events.
     */
    protected $entityChangeSet = [];

    /**
     * FilterLinkEvent constructor.
     *
     * @param LinkEntity $link Processed entity
     * @param array $entityChangeSet Change set for preUpdate events
     */
    public function __construct(LinkEntity $link, array $entityChangeSet = [])
    {
        $this->link = $link;
        $this->entityChangeSet = $entityChangeSet;
    }

    /**
     * Returns the entity.
     *
     * @return LinkEntity
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Returns the change set.
     *
     * @return array Entity change set
     */
    public function getEntityChangeSet()
    {
        return $this->entityChangeSet;
    }
}
