<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\Base;

/**
 * Events definition base class.
 */
abstract class AbstractDownlinkEvents
{
    /**
     * The rkdownlinkmodule.link_post_load event is thrown when links
     * are loaded from the database.
     *
     * The event listener receives an
     * RK\DownlinkModule\Event\FilterLinkEvent instance.
     *
     * @see RK\DownlinkModule\Listener\EntityLifecycleListener::postLoad()
     * @var string
     */
    const LINK_POST_LOAD = 'rkdownlinkmodule.link_post_load';
    
    /**
     * The rkdownlinkmodule.link_pre_persist event is thrown before a new link
     * is created in the system.
     *
     * The event listener receives an
     * RK\DownlinkModule\Event\FilterLinkEvent instance.
     *
     * @see RK\DownlinkModule\Listener\EntityLifecycleListener::prePersist()
     * @var string
     */
    const LINK_PRE_PERSIST = 'rkdownlinkmodule.link_pre_persist';
    
    /**
     * The rkdownlinkmodule.link_post_persist event is thrown after a new link
     * has been created in the system.
     *
     * The event listener receives an
     * RK\DownlinkModule\Event\FilterLinkEvent instance.
     *
     * @see RK\DownlinkModule\Listener\EntityLifecycleListener::postPersist()
     * @var string
     */
    const LINK_POST_PERSIST = 'rkdownlinkmodule.link_post_persist';
    
    /**
     * The rkdownlinkmodule.link_pre_remove event is thrown before an existing link
     * is removed from the system.
     *
     * The event listener receives an
     * RK\DownlinkModule\Event\FilterLinkEvent instance.
     *
     * @see RK\DownlinkModule\Listener\EntityLifecycleListener::preRemove()
     * @var string
     */
    const LINK_PRE_REMOVE = 'rkdownlinkmodule.link_pre_remove';
    
    /**
     * The rkdownlinkmodule.link_post_remove event is thrown after an existing link
     * has been removed from the system.
     *
     * The event listener receives an
     * RK\DownlinkModule\Event\FilterLinkEvent instance.
     *
     * @see RK\DownlinkModule\Listener\EntityLifecycleListener::postRemove()
     * @var string
     */
    const LINK_POST_REMOVE = 'rkdownlinkmodule.link_post_remove';
    
    /**
     * The rkdownlinkmodule.link_pre_update event is thrown before an existing link
     * is updated in the system.
     *
     * The event listener receives an
     * RK\DownlinkModule\Event\FilterLinkEvent instance.
     *
     * @see RK\DownlinkModule\Listener\EntityLifecycleListener::preUpdate()
     * @var string
     */
    const LINK_PRE_UPDATE = 'rkdownlinkmodule.link_pre_update';
    
    /**
     * The rkdownlinkmodule.link_post_update event is thrown after an existing new link
     * has been updated in the system.
     *
     * The event listener receives an
     * RK\DownlinkModule\Event\FilterLinkEvent instance.
     *
     * @see RK\DownlinkModule\Listener\EntityLifecycleListener::postUpdate()
     * @var string
     */
    const LINK_POST_UPDATE = 'rkdownlinkmodule.link_post_update';
    
}
