<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\Validator\Constraints;

use RK\DownlinkModule\Validator\Constraints\Base\AbstractListEntryValidator;

/**
 * List entry validator.
 */
class ListEntryValidator extends AbstractListEntryValidator
{
    // here you can customise the validator
}
