<?php
/**
 * Downlink.
 *
 * @copyright Ralf Koester (RK)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @author Ralf Koester <ralf@familie-koester.de>.
 * @link http://k62.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio (https://modulestudio.de).
 */

namespace RK\DownlinkModule\Entity\Factory\Base;

use RK\DownlinkModule\Entity\LinkEntity;

/**
 * Entity initialiser class used to dynamically apply default values to newly created entities.
 */
abstract class AbstractEntityInitialiser
{
    /**
     * Initialises a given link instance.
     *
     * @param LinkEntity $entity The newly created entity instance
     *
     * @return LinkEntity The updated entity instance
     */
    public function initLink(LinkEntity $entity)
    {

        return $entity;
    }

}
